### ISSUE TITLE
About description

### ISSUE THREAD

**Issue by jwe4ec** [jwe4ec/ttt-p2-cleaning#1]
Consider changing About description from "Centralized data cleaning for TRACL-to-TREAT Study" to "Centralized data cleaning for Phase II of TRACK-to-TREAT Study"

**Comment by jwe4ec** [comment]
We could also remove the Packages section from the repo's landing page given that it's unlikely we'll create any packages. The section could be added back later if needed.

**Comment by yamachang** [comment]
Done! Thank you for the suggestions, Jeremy!
